# example json creation:

createdBy <- 'Henrik John'
organizationName <- 'Erasmus University Medical Center'
outputLocation <- 'S:/hjohn/EmcMehtaDementiaModel'

settings <- data.frame(targetCohortId = c(18899),
                       targetCohortName = c('Mehta Target 0 Prior 0 Post [V2]'),
                       outcomeId = c(20554),
                       outcomeName = c('Mehta Outcome'))


populationSetting <- PatientLevelPrediction::createStudyPopulationSettings(binary = T,
                                                                           includeAllOutcomes = T, 
                                                                           firstExposureOnly = T, 
                                                                           washoutPeriod = 365, 
                                                                           removeSubjectsWithPriorOutcome = F, 
                                                                           priorOutcomeLookback = 9999, 
                                                                           requireTimeAtRisk = T, 
                                                                           minTimeAtRisk = 365, 
                                                                           riskWindowStart = 1, 
                                                                           startAnchor = 'cohort start', 
                                                                           endAnchor = 'cohort start', 
                                                                           riskWindowEnd = 365*5, 
                                                                           verbosity = 'INFO')

modelList <- list()
#length(modelList) <- 2
modelList[[1]] <- createModelJson(modelname = 'mehta_dementia_model', 
                                  modelFunction = 'glm',
                                  standardCovariates = data.frame(covariateId = c(1002,
                                                                                  8507001),
                                                                  covariateName = c('age in years',
                                                                                    'Male'),
                                                                  points = c(0.12,
                                                                             -0.08),
                                                                  featureExtraction = c('useDemographicsAge',
                                                                                        'useDemographicsGender')),
                                  cohortCovariateSettings = list(atlasCovariateIds = c(18416,
                                                                                       18417,
                                                                                       20553,
                                                                                       18419,
                                                                                       18420,
                                                                                       18463,
                                                                                       18464,
                                                                                       18465,
                                                                                       18543,
                                                                                       18545,
                                                                                       18546,
                                                                                       18547,
                                                                                       18548,
                                                                                       18549,
                                                                                       18552,
                                                                                       18553,
                                                                                       18554,
                                                                                       18555,
                                                                                       18556,
                                                                                       18558,
                                                                                       18562,
                                                                                       18563,
                                                                                       18564,
                                                                                       18566),
                                                                 atlasCovariateNames = c("Myocardial infarction",
                                                                                         "Congestive heart failure",
                                                                                         "Coronary and peripheral vascular disease",
                                                                                         "Cerebrovascular disease",
                                                                                         "Chronic pulmonary disease",
                                                                                         "Rheumatologic disease",
                                                                                         "Peptic ulcer disease",
                                                                                         "Renal disease and end stage renal disease",
                                                                                         "Mild liver disease and moderate or severe liver disease",
                                                                                         "Any malignancy",
                                                                                         "Epilepsy",
                                                                                         "Hyperlipidemia",
                                                                                         "Parkinson’s disease",
                                                                                         "Cardiac disease ASCVD",
                                                                                         "Glaucoma",
                                                                                         "Transplantation",
                                                                                         "Thyroid disorder",
                                                                                         "Gout",
                                                                                         "Crohn’s and ulcerative disease",
                                                                                         "Pain and inflammation and pain",
                                                                                         "Depression",
                                                                                         "Psychotic illness",
                                                                                         "Bipolar disorders",
                                                                                         "Anxiety and tension"),
                                                                 analysisIds = rep(456, 24),
                                                                 startDays = rep(-365, 24),
                                                                 endDays = rep(0, 24),
                                                                 points = c(-0.16,
                                                                            -0.11,
                                                                            0.15,
                                                                            0.36,
                                                                            -0.09,
                                                                            -0.07,
                                                                            -0.07,
                                                                            0.08,
                                                                            0.06,
                                                                            -0.01,
                                                                            0.33,
                                                                            0.10,
                                                                            0.78,
                                                                            -0.01,
                                                                            0.01,
                                                                            -0.18,
                                                                            0.05,
                                                                            -0.15,
                                                                            -0.06,
                                                                            -0.15,
                                                                            0.61,
                                                                            0.63,
                                                                            0.04,
                                                                            0.05),
                                                                 count = rep(F, 24),
                                                                 ageInteraction = rep(F, 24),
                                                                 lnAgeInteraction = rep(F, 24)
                                  ),
                                  
                                  measurementCovariateSettings = NULL, 
                                  measurementCohortCovariateSettings = NULL, 
                                  ageCovariateSettings = NULL,
                                  finalMapping = 'function(x){return(x)}',
                                  predictionType = 'survival'
)


jsonSet <- createStudyJson(packageName = 'EmcMehtasDementiaModel',
                packageDescription = 'Mehta model replicated by EMC',
                createdBy = createdBy ,
                organizationName = organizationName,
                settings = settings,
                baseUrl = baseUrl,
                populationSetting = populationSetting ,
                modelList = modelList,
                outputLocation = outputLocation)


jsonSet <- Hydra::loadSpecifications(file.path(outputLocation,'existingModelSettings.json'))
Hydra::hydrate(specifications = jsonSet, 
               outputFolder = 'S:/hjohn/EmcMehtaDementiaModel')

