# example json creation:

createdBy <- 'Henrik John'
organizationName <- 'Erasmus University Medical Center'
outputLocation <- 'S:/hjohn/EmcDementiaModelValidation/EmcNoriDementiaModel'

settings <- data.frame(targetCohortId = c(20613),
                       targetCohortName = c("Nori Target 0 Prior 0 Post [v1]"),
                       outcomeId = c(20700),
                       outcomeName = c("Nori Outcome"))


populationSetting <- PatientLevelPrediction::createStudyPopulationSettings(binary = T,
                                                                           includeAllOutcomes = T, 
                                                                           firstExposureOnly = F, 
                                                                           washoutPeriod = 1825, 
                                                                           removeSubjectsWithPriorOutcome = F, 
                                                                           priorOutcomeLookback = 9999, 
                                                                           requireTimeAtRisk = T, 
                                                                           minTimeAtRisk = (365*3-1), 
                                                                           riskWindowStart = 1, 
                                                                           startAnchor = 'cohort start', 
                                                                           endAnchor = 'cohort start', 
                                                                           riskWindowEnd = (365*3), 
                                                                           verbosity = 'INFO')

modelList <- list()
#length(modelList) <- 2
modelList[[1]] <- createModelJson(modelname = 'nori_dementia_model', 
                                  modelFunction = 'glm',
                                  standardCovariates = NULL,
                                  cohortCovariateSettings = list(atlasCovariateIds = c(19557,
                                                                                       19558,
                                                                                       19559,
                                                                                       19560,
                                                                                       19561,
                                                                                       19562,
                                                                                       19563,
                                                                                       19564,
                                                                                       19565,
                                                                                       19566,
                                                                                       19567,
                                                                                       19568,
                                                                                       19569,
                                                                                       19570,
                                                                                       19571,
                                                                                       19572,
                                                                                       19735,
                                                                                       19736,
                                                                                       19737,
                                                                                       19738,
                                                                                       19739,
                                                                                       19740,
                                                                                       19741,
                                                                                       19742,
                                                                                       19749,
                                                                                       19750,
                                                                                       19751,
                                                                                       19752,
                                                                                       20581,
                                                                                       20582,
                                                                                       20583,
                                                                                       20584,
                                                                                       20589,
                                                                                       20590,
                                                                                       20591,
                                                                                       20592,
                                                                                       20593,
                                                                                       20594,
                                                                                       20595,
                                                                                       20597,
                                                                                       20598,
                                                                                       20599,
                                                                                       20600,
                                                                                       20601,
                                                                                       20602,
                                                                                       20603,
                                                                                       20605,
                                                                                       20606,
                                                                                       20607,
                                                                                       20608),
                                                                 atlasCovariateNames = c("MEMORY LOSS",
                                                                                         "PARALYSIS AGITANS",
                                                                                         "MILD COGNITIVE IMPAIRMENT SO STATED",
                                                                                         "BIPOLAR DISORDER UNSPECIFIED",
                                                                                         "UNSPECIFIED PSYCHOSIS",
                                                                                         "LOSS OF WEIGHT",
                                                                                         "DEPRESSIVE DISORDER NOT ELSEWHERE CLASSIFIED",
                                                                                         "ALTERED MENTAL STATUS",
                                                                                         "PERSONAL HISTORY OF FALL",
                                                                                         "OTHER CONVULSIONS",
                                                                                         "UNSPECIFIED FALL",
                                                                                         "OTHER CHRONIC PAIN",
                                                                                         "ACUTE BUT ILLDEFINED CEREBROVASCULAR DISEASE",
                                                                                         "URGE INCONTINENCE",
                                                                                         "OTHER ALTERATION OF CONSCIOUSNESS",
                                                                                         "UNSPECIFIED CONSTIPATION",
                                                                                         "UNSPECIFIED URINARY INCONTINENCE",
                                                                                         "ENCOUNTER FOR LONGTERM CURRENT USE OF OTHER MEDICATIONS",
                                                                                         "LACK OF COORDINATION",
                                                                                         "OTHER MALAISE AND FATIGUE",
                                                                                         "DIABETES MELLITUS",
                                                                                         "ABNORMALITY OF GAIT",
                                                                                         "DIZZINESS AND GIDDINESS",
                                                                                         "UNSPECIFIED CEREBRAL ARTERY OCCLUSION WITH CEREBRAL INFARCTION",
                                                                                         "DIABETES MELLITUS 2",
                                                                                         "EDEMA",
                                                                                         "MUSCLE WEAKNESS GENERALIZED",
                                                                                         "URINARY TRACT INFECTION SITE NOT SPECIFIED",
                                                                                         "SCREENING MAMMOGRAPHY COMPUTERAIDED DETECTION",
                                                                                         "COMPUTED TOMOGRAPHY HEAD OR BRAIN",
                                                                                         "RADIOLOGIC EXAMINATION CHEST SINGLE VIEW FRONTAL",
                                                                                         "VENLAFAXINE HCL",
                                                                                         "DULOXETINE HCL",
                                                                                         "TOLTERODINE TARTRATE",
                                                                                         "SERTRALINE HCL",
                                                                                         "CITALOPRAM HYDROBROMIDE",
                                                                                         "POTASSIUM CHLORIDE",
                                                                                         "OXYBUTYNIN CHLORIDE",
                                                                                         "HYDROCODONE BIT ACETAMINOPHEN",
                                                                                         "PROPOXYPHENE ACETAMINOPHEN",
                                                                                         "SULFAMETHOXAZOLE TRIMETHOPRIM",
                                                                                         "METFORMIN HCL",
                                                                                         "BLOOD SUGAR DIAGNOSTIC",
                                                                                         "LISINOPRIL",
                                                                                         "CEPHALEXIN MONOHYDRATE",
                                                                                         "SIMVASTATIN",
                                                                                         "CLOPIDOGREL BISULFATE",
                                                                                         "TRAMADOL HCL",
                                                                                         "GABAPENTIN",
                                                                                         "FUROSEMIDE"),
                                                                 analysisIds = rep(456, 50),
                                                                 startDays = rep(-1825, 50),
                                                                 endDays = rep(-1095, 50),
                                                                 points = c(1.33,
                                                                            1.17,
                                                                            1.14,
                                                                            1.00,
                                                                            0.44,
                                                                            0.42,
                                                                            0.37,
                                                                            0.33,
                                                                            0.32,
                                                                            0.32,
                                                                            0.27,
                                                                            0.28,
                                                                            0.24,
                                                                            0.24,
                                                                            0.23,
                                                                            0.21,
                                                                            0.21,
                                                                            0.17,
                                                                            0.15,
                                                                            0.11,
                                                                            0.12,
                                                                            0.10,
                                                                            0.11,
                                                                            0.11,
                                                                            0.07,
                                                                            0.07,
                                                                            0.06,
                                                                            0.03,
                                                                            -0.25,
                                                                            0.16,
                                                                            0.05,
                                                                            0.52,
                                                                            0.45,
                                                                            0.32,
                                                                            0.29,
                                                                            0.25,
                                                                            0.24,
                                                                            0.22,
                                                                            0.19,
                                                                            0.15,
                                                                            0.15,
                                                                            0.13,
                                                                            0.12,
                                                                            0.11,
                                                                            0.10,
                                                                            0.10,
                                                                            0.09,
                                                                            0.09,
                                                                            0.07,
                                                                            0.00),
                                                                 count = rep(F, 50),
                                                                 ageInteraction = rep(F, 50),
                                                                 lnAgeInteraction = rep(F, 50)
                                  ),
                                  
                                  measurementCovariateSettings = NULL, 
                                  measurementCohortCovariateSettings = NULL, 
                                  ageCovariateSettings = NULL,
                                  finalMapping = 'function(x){return(1/(1+exp(-(-1.96+x))))}',
                                  predictionType = 'binary'
)


jsonSet <- createStudyJson(packageName = 'EmcNoriDementiaModel',
                packageDescription = 'Nori model replicated by EMC',
                createdBy = createdBy ,
                organizationName = organizationName,
                settings = settings,
                baseUrl = baseUrl,
                populationSetting = populationSetting ,
                modelList = modelList,
                outputLocation = outputLocation)


jsonSet <- Hydra::loadSpecifications(file.path(outputLocation,'existingModelSettings.json'))
Hydra::hydrate(specifications = jsonSet, 
               outputFolder = 'S:/hjohn/EmcDementiaModelValidation/EmcNoriDementiaModel')

